services:
  db:
    image: mysql:8.0
    container_name: tp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jpa
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: tp-admin-api:1.0
    container_name: tp-admin-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/jpa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234
      DB_HOST: db
    ports:
      - "8081:8081"

volumes:
  db_data:
