name: Build, Push to ECR

on:
  workflow_dispatch: # 수동 실행을 위한 트리거 추가

permissions:
  id-token: write
  contents: read

jobs:
  # =================================================
  # 1. Build Job: 이미지를 빌드하고 ECR에 푸시
  # =================================================
  build:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    # 이 작업의 결과물(outputs)을 다른 작업에서 사용할 수 있도록 명시적으로 선언합니다.
    outputs:
      image_uri: ${{ steps.push-image.outputs.image_uri }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          FULL_IMAGE_NAME="$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker build -t $FULL_IMAGE_NAME .
          echo "FULL_IMAGE_NAME=$FULL_IMAGE_NAME" >> $GITHUB_ENV

      - name: Push Docker image
        id: push-image
        env:
          FULL_IMAGE_NAME: ${{ env.FULL_IMAGE_NAME }}
        run: |
          docker push $FULL_IMAGE_NAME
          echo "image_uri=$FULL_IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Create imagedefinitions.json for CodeDeploy
        env:
          IMAGE_URI: ${{ steps.push-image.outputs.image_uri }}
          CONTAINER_NAME: ${{ vars.CONTAINER_NAME }}
        run: |
          echo "Received Image URI to deploy: $IMAGE_URI"
          printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$IMAGE_URI" > imagedefinitions.json
          echo "Generated imagedefinitions.json content:"
          cat imagedefinitions.json

      - name: Upload imagedefinitions.json to S3
        run: aws s3 cp imagedefinitions.json s3://$S3_BUCKET/imagedefinitions.json